---
output: pdf_document
urlcolor: blue
---

# How can ornithologists find R packages?

By *Steffi LaZerte* (Stefanie E. LaZerte)    
[steffilazerte.ca](https://steffilazerte.ca) / Brandon University  

Twitter `r icons::ionicons('logo-twitter')` @steffilazerte  
GitHub `r icons::ionicons('logo-github')` steffilazerte  


Thanks for checking out my talk!

**Slides**  

- [HTML](https://steffilazerte.ca/Presentations/2021-08%20AOS%7CSOC%20-%20R%20Symposium/AOS_SCO_2021_LaZerte.html)
- [PDF](https://steffilazerte.ca/Presentations/2021-08%20AOS%7CSOC%20-%20R%20Symposium/AOS_SCO_2021_LaZerte.pdf)
- [Source (RMD)](https://github.com/steffilazerte/Presentations/tree/master/2021-08%20AOS%7CSOC%20-%20R%20Symposium)

## Abstract

R is powerful free and open-source software (FOSS) for statistical programming. Because R is FOSS it reduces financial barriers to conducting science and is therefore used by ornithologists all over the world with different backgrounds and experiences. R can be extended with “packages” developed by this community, but exploring the thousands of packages available can be overwhelming. In this lighting talk I will share tips, tricks, and resources to help ornithologists find great R packages which can make their work faster, easier, more robust, and reproducible.


R est un puissant logiciel en source libre et ouvert pour la programmation statistique. Par conséquent, R réduit les obstacles financiers à la conduite de la science et est donc utilisé par des ornithologues du monde entier avec des antécédents et des expériences différents. R peut être étendu avec des «packages» développés par cette communauté, mais explorer les milliers de packages disponibles peut être écrasant. Dans cet exposé, je partagerai des conseils, des astuces et des ressources pour aider les ornithologues à trouver d'excellents packages qui peuvent rendre leur travail plus rapide, plus facile, plus robuste et reproductible.
